
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANIMATE BLUE COLOR_WIPE COMA GREEN LP NUMBER ORANGE PURPLE RAINBOW RANDOW_CYCLE RED RGB RP THEATER_CHASE THEATER_CHASE_RAINBOW WHITE YELLOW\n    run : command\n        | empty\n    \n    command : ANIMATE animation color miliseconds\n    \n    miliseconds : NUMBER\n    \n  color : RED\n        | BLUE\n        | GREEN\n        | YELLOW\n        | ORANGE\n        | PURPLE\n        | WHITE\n  \n  animation : RAINBOW\n            | RANDOW_CYCLE\n            | THEATER_CHASE_RAINBOW\n            | COLOR_WIPE\n            | THEATER_CHASE\n  \n    empty :\n    '
    
_lr_action_items = {'ANIMATE':([0,],[4,]),'$end':([0,1,2,3,19,20,],[-17,0,-1,-2,-3,-4,]),'RAINBOW':([4,],[6,]),'RANDOW_CYCLE':([4,],[7,]),'THEATER_CHASE_RAINBOW':([4,],[8,]),'COLOR_WIPE':([4,],[9,]),'THEATER_CHASE':([4,],[10,]),'RED':([5,6,7,8,9,10,],[12,-12,-13,-14,-15,-16,]),'BLUE':([5,6,7,8,9,10,],[13,-12,-13,-14,-15,-16,]),'GREEN':([5,6,7,8,9,10,],[14,-12,-13,-14,-15,-16,]),'YELLOW':([5,6,7,8,9,10,],[15,-12,-13,-14,-15,-16,]),'ORANGE':([5,6,7,8,9,10,],[16,-12,-13,-14,-15,-16,]),'PURPLE':([5,6,7,8,9,10,],[17,-12,-13,-14,-15,-16,]),'WHITE':([5,6,7,8,9,10,],[18,-12,-13,-14,-15,-16,]),'NUMBER':([11,12,13,14,15,16,17,18,],[20,-5,-6,-7,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'run':([0,],[1,]),'command':([0,],[2,]),'empty':([0,],[3,]),'animation':([4,],[5,]),'color':([5,],[11,]),'miliseconds':([11,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> run","S'",1,None,None,None),
  ('run -> command','run',1,'p_run','LightUp.py',116),
  ('run -> empty','run',1,'p_run','LightUp.py',117),
  ('command -> ANIMATE animation color miliseconds','command',4,'p_command','LightUp.py',123),
  ('miliseconds -> NUMBER','miliseconds',1,'p_miliseconds','LightUp.py',129),
  ('color -> RED','color',1,'p_color','LightUp.py',134),
  ('color -> BLUE','color',1,'p_color','LightUp.py',135),
  ('color -> GREEN','color',1,'p_color','LightUp.py',136),
  ('color -> YELLOW','color',1,'p_color','LightUp.py',137),
  ('color -> ORANGE','color',1,'p_color','LightUp.py',138),
  ('color -> PURPLE','color',1,'p_color','LightUp.py',139),
  ('color -> WHITE','color',1,'p_color','LightUp.py',140),
  ('animation -> RAINBOW','animation',1,'p_animation','LightUp.py',146),
  ('animation -> RANDOW_CYCLE','animation',1,'p_animation','LightUp.py',147),
  ('animation -> THEATER_CHASE_RAINBOW','animation',1,'p_animation','LightUp.py',148),
  ('animation -> COLOR_WIPE','animation',1,'p_animation','LightUp.py',149),
  ('animation -> THEATER_CHASE','animation',1,'p_animation','LightUp.py',150),
  ('empty -> <empty>','empty',0,'p_empty','LightUp.py',156),
]
