ARRDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyAACM*

                      #Probably ubuntu
USER_LIB_PATH = /home/THISWILLCHANGE/sketchbook/libraries
BOARD_TAG = uno   #arduino type

include /usr/share/arduino/Arduino.mk